### ISSUE TITLE
styled-component의 theme 사용 오류

### ISSUE THREAD

**Issue by ycs1m1yk** [FE-CheckList-Gallery/FE-CheckList-Gallery#6]
**Describe the bug**
TagList.tsx에서 TagList 컴포넌트의 css를 작성할 때 아래의 코드로 theme색을 사용하려고 합니다.
```js
${(props) => props.theme.palette.africanviolet};
```
`이 호출과 일치하는 오버로드가 없습니다.` 라는 오류가 발생했습니다.

**To Reproduce**
컴포넌트를 작성하며 styled-components의 theme에 정의된 값을 사용합니다.

**Expected behavior**
에러메세지 없이 theme색 사용.

**Screenshots**
![image](https://user-images.githubusercontent.com/27720475/173579076-6524dbc3-5e7e-418e-8907-1c85961d19b8.png)

**Desktop (please complete the following information):**
 - OS: 윈도우
 - Version 10

**Additional context**

**Comment by ycs1m1yk** [comment]
타입스크립트 관련해서 찾아보니

`Number`, `String`, `Boolean`, `Symbol`, `Object` 와 같은 일반 타입을 사용하지 말라고 합니다.

https://www.typescriptlang.org/ko/docs/handbook/declaration-files/do-s-and-don-ts.html#%EC%9D%BC%EB%B0%98-%ED%83%80%EC%9E%85-general-types

`src > styles > style.d.ts` 코드에서

DefaultTheme 인터페이스의 타입들을 `String` -> `string` 으로 고치면 될 것 같습니다.

**Comment by gomiseki** [comment]
실수가 있었네요.... 이게 다 몽구스 때문입니다ㅋㅋ
